name: Compile documentation
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pages

      - uses: actions/checkout@v4
        with:
          repository: Jelly-RDF/jelly-protobuf
          path: proto

      - name: Generate Protobuf reference
        run: |
          docker run --rm -v $(pwd):/proto -v $(pwd)/pages/docs/specification:/out pseudomuto/protoc-gen-doc --doc_opt=markdown,reference.md
          cd pages

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Deploy site
        run: |
          git fetch origin gh-pages --depth=1
          git config user.name ci-bot
          git config user.email ci-bot@example.com
          mike deploy --push --update-aliases 1.0 latest
