name: Test documentation compilation

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pages
          fetch-depth: 0
          submodules: recursive

      - uses: actions/checkout@v4
        with:
          repository: Jelly-RDF/jelly-protobuf
          sparse-checkout: proto
          path: p
          submodules: recursive

      - id: jvm_release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          owner: Jelly-RDF
          repo: jelly-jvm
          excludes: prerelease, draft

      - name: Generate Protobuf reference
        run: |
          mkdir -p pages/docs/specification/proto
          cp p/proto/*.proto pages/docs/specification/proto
          # Remove double newlines in comments to avoid breaking markdown tables
          # See: https://github.com/pseudomuto/protoc-gen-doc/issues/274
          find p/proto/*.proto -type f -exec perl -0777 -i -pe "s|\n[ \t]+//[ \t]*\n|\n|igs" {} \;
          find p/proto/*.proto -type f -exec perl -0777 -i -pe "s|(https?[^\s]+)|[\1](\1)|igs" {} \;
          docker run --rm -v $(pwd)/p/proto:/protos -v $(pwd)/pages/docs/specification:/out pseudomuto/protoc-gen-doc --doc_opt=markdown,reference.md

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: 'pages/requirements.txt'
  
      - name: Install dependencies
        working-directory: ./pages
        run: pip install -r requirements.txt

      - name: Build documentation
        working-directory: ./pages
        run: |
          export TAG='main'
          export PYTHON_TAG='main'
          export JVM_TAG='main'
          export JVM_LATEST_RELEASE='${{ steps.jvm_release.outputs.release }}'
          export PROTO_PATH='../p/proto'
          mkdocs build -s
